//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion.partes.incidencias.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tfgEntities : DbContext
    {
        public tfgEntities()
            : base("name=tfgEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alumno> alumno { get; set; }
        public virtual DbSet<grupo> grupo { get; set; }
        public virtual DbSet<motivo_amonestacion> motivo_amonestacion { get; set; }
        public virtual DbSet<permiso> permiso { get; set; }
        public virtual DbSet<permisos_rol> permisos_rol { get; set; }
        public virtual DbSet<profesor> profesor { get; set; }
        public virtual DbSet<registro> registro { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<roles_profesor> roles_profesor { get; set; }
        public virtual DbSet<tipo_registro> tipo_registro { get; set; }
    }
}
