//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion.partes.incidencias.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class motivo_registro
    {
        public int id { get; set; }
        public Nullable<int> id_tipo_registro { get; set; }
        public string motivo { get; set; }
        public string descripcion { get; set; }
    
        public virtual tipo_registro tipo_registro { get; set; }
    }
}
