//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion.partes.incidencias.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class registro
    {
        public int id { get; set; }
        public Nullable<int> id_tipo_registro { get; set; }
        public Nullable<int> id_motivo_registro { get; set; }
        public Nullable<System.DateTime> fecha_suceso { get; set; }
        public Nullable<int> nia_alumno { get; set; }
        public string dni_profesor { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string dni_profesor_registro { get; set; }
        public Nullable<bool> sancionado { get; set; }
    
        public virtual alumno alumno { get; set; }
        public virtual profesor profesor { get; set; }
        public virtual profesor profesor1 { get; set; }
        public virtual tipo_registro tipo_registro { get; set; }
    }
}
